version: 3
project:
  id: github.com/Zofikar/kartkoweczka
  name: Zofikar/Kartkoweczka
  url: https://github.com/Zofikar/kartkoweczka

targets:
  only:
    - type: yarn
      path: .
    - type: cargo
      path: src-tauri

telemetry:
  scope: 'off'
