version: 3
project:
  id: gitea.internal/Pawel/Kartkoweczka
  name: Pawel/Kartkoweczka
  url: https://gitea.internal/Pawel/Kartkoweczka

targets:
  only:
    - type: yarn
      path: .

referenced-dependencies:
  - type: git
    name: https://github.com/opencv/opencv.git
    version: '4.14.0'

telemetry:
  scope: 'off'
