name: Code Quality Check

on:
  push:
    paths:
      - '**.svelte'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '**.css'
      - '**.html'
      - '*.yaml'
      - '*.yml'
      - 'svelte.config.js'
      - 'vite.config.ts'
      - 'eslint.config.js'
      - 'tsconfig.json'
      - 'tsconfig.app.json'
      - 'tsconfig.node.json'
      - '.prettierrc'
  pull_request:
    paths:
      - '**.svelte'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '**.css'
      - '**.html'
      - '*.yaml'
      - '*.yml'
      - 'svelte.config.js'
      - 'vite.config.ts'
      - 'eslint.config.js'
      - 'tsconfig.json'
      - 'tsconfig.app.json'
      - 'tsconfig.node.json'
      - '.prettierrc'

jobs:
  lint:
    name: Static Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.gitea/actions/setup/action.yaml

      - name: Run lint and format check
        run: yarn run lint

      - name: Run type check
        run: yarn run check
