/**
 * Answer sheet OMR (optical mark recognition) layout constants.
 *
 * The OMR block is the fixed-geometry part of the answer sheet: it always has
 * exactly the same physical size and internal layout, no matter which test or
 * revision is printed. All positions are expressed in *design units* — an
 * arbitrary internal coordinate space of {@link OMR_DESIGN_WIDTH} ×
 * {@link OMR_DESIGN_HEIGHT} units that maps 1:1 to millimetres via
 * {@link OMR_UNITS_PER_MM} and is rendered through `FixedCanvas`.
 *
 * A scanner rectifies a photo/scan of the block by detecting the four ArUco
 * corner markers, computing a homography from their known positions, and
 * warping the block back to the canonical design-space rectangle. Every other
 * element (QR codes, future bubble grid) then sits at a known coordinate.
 *
 * This module is the single source of truth for that geometry — the print
 * renderer now and the scanner later must both use it.
 */

/**
 * Version of the answer-sheet layout, encoded in a QR code on every sheet.
 * Bump this whenever any constant in this file changes so future scanners can
 * tell which layout algorithm to apply.
 */
export const ANSWER_SHEET_FORMAT_VERSION = 2;

/** Physical width of the OMR block in millimetres (full usable A4 width). */
export const OMR_BLOCK_WIDTH_MM = 180;

/** Physical height of the OMR block in millimetres. */
export const OMR_BLOCK_HEIGHT_MM = 205;

/** Design units per millimetre — the internal resolution of the OMR block. */
export const OMR_UNITS_PER_MM = 10;

/** Internal design-space size of the OMR block (always the same). */
export const OMR_DESIGN_WIDTH = OMR_BLOCK_WIDTH_MM * OMR_UNITS_PER_MM;
export const OMR_DESIGN_HEIGHT = OMR_BLOCK_HEIGHT_MM * OMR_UNITS_PER_MM;

/**
 * ArUco dictionary the corner markers come from: the original ArUco
 * dictionary (5×5 data cells, ids 0–1023), generated by the `aruco-marker`
 * package. Detectable by OpenCV's DICT_ARUCO_ORIGINAL and by js-aruco.
 */
export const ARUCO_DICTIONARY_NAME = 'ARUCO_ORIGINAL';

/**
 * Curated ARUCO_ORIGINAL ids for reliable printing and detection.
 *
 * The pool was selected from all 1024 markers using these constraints:
 * - 8..17 white data cells;
 * - 8..18 internal black/white transitions;
 * - at least 10 bits from the marker's own rotations;
 * - at least 10 bits between every selected marker under every rotation.
 *
 * Keep these ids together: their pairwise distance is part of the contract.
 */
export const ARUCO_TOP_LEFT_ANCHOR_ID = 37;
export const ARUCO_TOP_RIGHT_ANCHOR_ID = 336;
export const ARUCO_BOTTOM_RIGHT_ANCHOR_ID = 575;
export const ARUCO_FORMAT_VERSION_IDS = [79, 426, 837, 896, 382, 224] as const;

/** ArUco marker edge length in design units (80 = 8 mm, roughly text-line sized). */
export const ARUCO_MARKER_SIZE = 80;

/** Inset of each marker's outer edge from the block edges, in design units. */
export const ARUCO_MARKER_INSET = 50;

/** Extra reserved space around scanner fiducials, in design units. */
export const OMR_EXCLUSION_PADDING = 40;

export type OmrCorner = 'tl' | 'tr' | 'br' | 'bl';

export interface OmrRect {
	x: number;
	y: number;
	width: number;
	height: number;
}

export interface ArucoMarkerPlacement extends OmrRect {
	corner: OmrCorner;
	/** Marker id. TL/TR/BR are fixed anchors; BL encodes the format version. */
	id: number;
}

export interface OmrExclusionZone extends OmrRect {
	key: string;
	label: string;
}

/**
 * Top-left origins of the four corner markers, in design units.
 *
 * Marker ids use three fixed orientation anchors and one format-version marker:
 * - TL, TR, and BR identify their corners unambiguously;
 * - BL identifies the answer-sheet format version through a curated marker pool.
 *
 * Revision metadata belongs exclusively to the QR code. Marker geometry therefore
 * stays stable for every revision using the same answer-sheet format.
 */
export function arucoMarkerPlacements(): ArucoMarkerPlacement[] {
	const farX = OMR_DESIGN_WIDTH - ARUCO_MARKER_INSET - ARUCO_MARKER_SIZE;
	const farY = OMR_DESIGN_HEIGHT - ARUCO_MARKER_INSET - ARUCO_MARKER_SIZE;
	return [
		markerPlacement('tl', ARUCO_TOP_LEFT_ANCHOR_ID, ARUCO_MARKER_INSET, ARUCO_MARKER_INSET),
		markerPlacement('tr', ARUCO_TOP_RIGHT_ANCHOR_ID, farX, ARUCO_MARKER_INSET),
		markerPlacement('br', ARUCO_BOTTOM_RIGHT_ANCHOR_ID, farX, farY),
		markerPlacement(
			'bl',
			arucoFormatVersionMarkerId(ANSWER_SHEET_FORMAT_VERSION),
			ARUCO_MARKER_INSET,
			farY
		),
	];
}

function markerPlacement(
	corner: OmrCorner,
	id: number,
	x: number,
	y: number
): ArucoMarkerPlacement {
	return { corner, id, x, y, width: ARUCO_MARKER_SIZE, height: ARUCO_MARKER_SIZE };
}

/** Return the curated marker id assigned to a one-based answer-sheet format version. */
export function arucoFormatVersionMarkerId(formatVersion: number): number {
	const markerId = ARUCO_FORMAT_VERSION_IDS[formatVersion - 1];
	if (markerId === undefined) {
		throw new Error(`Brak markera ArUco dla formatu karty odpowiedzi v${formatVersion}.`);
	}
	return markerId;
}

/** Return the one-based answer-sheet format version encoded by a curated marker id. */
export function answerSheetFormatVersionFromMarkerId(markerId: number): number | undefined {
	const index = ARUCO_FORMAT_VERSION_IDS.indexOf(
		markerId as (typeof ARUCO_FORMAT_VERSION_IDS)[number]
	);
	return index === -1 ? undefined : index + 1;
}

/** QR code edge length in design units (180 = 18 mm). */
export const QR_CODE_SIZE = 180;

/** Gap between right-side fiducials and metadata QR, in design units. */
export const QR_METADATA_MARKER_GAP = 60;

/**
 * The full answer grid design plane. Future bubbles may use this whole area as
 * long as they avoid `omrExclusionZones(...)`.
 */
export const GRID_AREA = {
	x: 0,
	y: 0,
	width: OMR_DESIGN_WIDTH,
	height: OMR_DESIGN_HEIGHT,
} as const;

export function metadataQrPlacement(): OmrRect {
	return {
		x: OMR_DESIGN_WIDTH - ARUCO_MARKER_INSET - QR_CODE_SIZE,
		y:
			OMR_DESIGN_HEIGHT -
			ARUCO_MARKER_INSET -
			ARUCO_MARKER_SIZE -
			QR_METADATA_MARKER_GAP -
			QR_CODE_SIZE,
		width: QR_CODE_SIZE,
		height: QR_CODE_SIZE,
	};
}

/** Reserved areas future bubble/grid content must avoid. */
export function omrExclusionZones(): OmrExclusionZone[] {
	return [
		...arucoMarkerPlacements().map((marker) =>
			exclusionZone(`aruco-${marker.corner}`, `ArUco ${marker.corner.toUpperCase()}`, marker)
		),
		exclusionZone('metadata-qr', 'QR metadanych', metadataQrPlacement()),
	];
}

function exclusionZone(key: string, label: string, rect: OmrRect): OmrExclusionZone {
	return {
		key,
		label,
		x: Math.max(0, rect.x - OMR_EXCLUSION_PADDING),
		y: Math.max(0, rect.y - OMR_EXCLUSION_PADDING),
		width:
			Math.min(OMR_DESIGN_WIDTH, rect.x + rect.width + OMR_EXCLUSION_PADDING) -
			Math.max(0, rect.x - OMR_EXCLUSION_PADDING),
		height:
			Math.min(OMR_DESIGN_HEIGHT, rect.y + rect.height + OMR_EXCLUSION_PADDING) -
			Math.max(0, rect.y - OMR_EXCLUSION_PADDING),
	};
}

/** Payload of the sheet metadata QR code. Keep keys short to keep the QR compact. */
export function sheetMetadataQrPayload(revisionId: string): string {
	return JSON.stringify({ r: revisionId, f: ANSWER_SHEET_FORMAT_VERSION });
}

/** Convert design units to millimetres. */
export function omrUnitsToMm(units: number): number {
	return units / OMR_UNITS_PER_MM;
}
