/**
 * Answer sheet OMR (optical mark recognition) configuration.
 *
 * The OMR block is the fixed-geometry part of the answer sheet: it always has
 * exactly the same physical size and internal layout for a given format
 * version. All positions are expressed in *design units* — an arbitrary
 * internal coordinate space of `geometry.designWidth` × `geometry.designHeight`
 * units that maps 1:1 to millimetres via `geometry.unitsPerMm` and is rendered
 * through `FixedCanvas`.
 *
 * A scanner rectifies a photo/scan of the block by detecting the four ArUco
 * corner markers, computing a homography from their known positions, and
 * warping the block back to the canonical design-space rectangle. Every other
 * element (QR codes, future bubble grid) then sits at a known coordinate.
 *
 * This module is the single source of truth for that geometry — the print
 * renderer and the scanner must both use it. Every format version has its own
 * {@link OmrConfig} entry in {@link OMR_CONFIG_VERSIONS}; bumping a version
 * means adding a new entry (and a new bottom-left ArUco version marker id),
 * never mutating an existing one.
 */

import { z } from 'zod/mini';

export type OmrCorner = 'tl' | 'tr' | 'br' | 'bl';

export interface OmrRect {
	x: number;
	y: number;
	width: number;
	height: number;
}

export interface ArucoMarkerPlacement extends OmrRect {
	corner: OmrCorner;
	/** Marker id. TL/TR/BR are fixed anchors; BL encodes the format version. */
	id: number;
}

export interface OmrExclusionZone extends OmrRect {
	key: string;
}

/** Physical size and design-space resolution of the OMR block. */
export interface OmrGeometryConfig {
	/** Physical width of the OMR block in millimetres. */
	blockWidthMm: number;
	/** Physical height of the OMR block in millimetres. */
	blockHeightMm: number;
	/** Design units per millimetre — the internal resolution of the OMR block. */
	unitsPerMm: number;
	/** Internal design-space width, derived: `blockWidthMm * unitsPerMm`. */
	designWidth: number;
	/** Internal design-space height, derived: `blockHeightMm * unitsPerMm`. */
	designHeight: number;
}

/** ArUco fiducial markers: anchors, version encoding, and placement geometry. */
export interface OmrArucoConfig {
	/**
	 * ArUco dictionary the corner markers come from: the original ArUco
	 * dictionary (5×5 data cells, ids 0–1023), generated by the `aruco-marker`
	 * package. Detectable by OpenCV's DICT_ARUCO_ORIGINAL.
	 */
	dictionaryName: 'ARUCO_ORIGINAL';
	/**
	 * Curated ARUCO_ORIGINAL ids of the three static corner anchors.
	 *
	 * Selected (like the version pool below) from all 1024 markers using these
	 * constraints:
	 * - 8..17 white data cells;
	 * - 8..18 internal black/white transitions;
	 * - at least 10 bits from the marker's own rotations;
	 * - at least 10 bits between every selected marker under every rotation.
	 *
	 * Keep these ids together with the version pool: their pairwise distance is
	 * part of the contract.
	 */
	anchorIds: {
		topLeft: number;
		topRight: number;
		bottomRight: number;
	};
	/**
	 * Curated ARUCO_ORIGINAL ids that encode the answer-sheet format version.
	 * The list index maps 1:1 to the one-based format version: a sheet of
	 * version N prints marker `formatVersionIds[N - 1]` in the bottom-left
	 * corner. This is the only thing a scanner needs to deduce the version.
	 */
	formatVersionIds: readonly number[];
	/** Marker edge length in design units (100 = 10 mm). */
	markerSize: number;
	/** Inset of each marker's outer edge from the block edges, in design units. */
	markerInset: number;
}

/**
 * Metadata carried by the sheet QR code.
 *
 * `revisionId` identifies the immutable test revision the sheet was printed
 * from; `formatVersion` mirrors the OMR format version (also encoded in the
 * bottom-left ArUco marker) so print and scan can cross-check.
 */
const sheetMetadataSchema = z.object({
	revisionId: z.uuid(),
});
export type SheetMetadata = z.infer<typeof sheetMetadataSchema>;

/** Sheet metadata QR code size, placement, and payload codec. */
export interface OmrQrCodeConfig {
	/** QR code edge length in design units (200 = 20 mm). */
	size: number;
	/**
	 * Encode sheet metadata into the QR code payload string.
	 * Inverse of {@link OmrQrCodeConfig.decodePayload}.
	 */
	encodePayload(metadata: SheetMetadata): string;
	/**
	 * Decode a QR code payload string back into sheet metadata.
	 * Returns `undefined` for any payload that is not valid metadata JSON.
	 * Inverse of {@link OmrQrCodeConfig.encodePayload}.
	 */
	decodePayload(data: string): Readonly<SheetMetadata> | undefined;
}

function sheetMetadataQrCodec(version: number) {
	return {
		encodePayload(metadata: SheetMetadata): string {
			return metadata.revisionId;
		},
		decodePayload(data: string): SheetMetadata | undefined {
			const {
				success,
				data: metadata,
				error,
			} = sheetMetadataSchema.safeParse({ revisionId: data });
			if (!success) {
				console.error(error, version);
				return undefined;
			}

			return metadata;
		},
	};
}

/** Answer grid (future bubbles) placement rules. */
export interface OmrGridConfig {
	/** Extra reserved space around scanner fiducials, in design units. */
	exclusionPadding: number;
}

/** Complete, self-contained configuration of one answer-sheet OMR format version. */
export interface OmrConfig {
	/** One-based answer-sheet format version, encoded in the QR and BL ArUco marker. */
	version: number;
	geometry: OmrGeometryConfig;
	aruco: OmrArucoConfig;
	qrCode: OmrQrCodeConfig;
	grid: OmrGridConfig;
}

interface OmrConfigInput {
	version: number;
	geometry: Omit<OmrGeometryConfig, 'designWidth' | 'designHeight'>;
	aruco: Omit<OmrArucoConfig, 'dictionaryName'> & { dictionaryName?: 'ARUCO_ORIGINAL' };
	qrCode: Omit<OmrQrCodeConfig, 'encodePayload' | 'decodePayload'>;
	grid: OmrGridConfig;
}

function defineOmrConfig(input: OmrConfigInput): OmrConfig {
	return {
		version: input.version,
		geometry: {
			...input.geometry,
			designWidth: input.geometry.blockWidthMm * input.geometry.unitsPerMm,
			designHeight: input.geometry.blockHeightMm * input.geometry.unitsPerMm,
		},
		aruco: {
			dictionaryName: input.aruco.dictionaryName ?? 'ARUCO_ORIGINAL',
			...input.aruco,
		},
		qrCode: {
			...input.qrCode,
			...sheetMetadataQrCodec(input.version),
		},
		grid: input.grid,
	};
}

/**
 * Known answer-sheet format configurations, indexed by version:
 * `OMR_CONFIG_VERSIONS[version - 1]` is the config for that version.
 * Never modify an existing entry — add a new one and bump the version.
 */
export const OMR_CONFIG_VERSIONS: readonly OmrConfig[] = [
	defineOmrConfig({
		version: 1,
		geometry: {
			blockWidthMm: 180,
			blockHeightMm: 205,
			unitsPerMm: 10,
		},
		aruco: {
			anchorIds: {
				topLeft: 37,
				topRight: 336,
				bottomRight: 575,
			},
			formatVersionIds: [79, 426, 837, 896, 382, 224],
			markerSize: 100,
			markerInset: 10,
		},
		qrCode: {
			size: 200,
		},
		grid: {
			exclusionPadding: 10,
		},
	}),
];

/** The newest known answer-sheet format configuration — used for printing. */
export const LATEST_OMR_CONFIG: OmrConfig = OMR_CONFIG_VERSIONS[OMR_CONFIG_VERSIONS.length - 1];

/** Return the configuration for a one-based answer-sheet format version. */
export function omrConfigForVersion(version: number): OmrConfig {
	const config = OMR_CONFIG_VERSIONS[version - 1];
	if (!config) {
		throw new Error(`Brak konfiguracji OMR dla formatu karty odpowiedzi v${version}.`);
	}
	return config;
}

/**
 * Canonical placements of the four corner markers, in design units.
 *
 * Marker ids use three fixed orientation anchors and one format-version marker:
 * - TL, TR, and BR identify their corners unambiguously;
 * - BL identifies the answer-sheet format version through a curated marker pool.
 *
 * Revision metadata belongs exclusively to the QR code. Marker geometry therefore
 * stays stable for every revision using the same answer-sheet format.
 */
export function arucoMarkerPlacements(config: OmrConfig): ArucoMarkerPlacement[] {
	const { designWidth, designHeight } = config.geometry;
	const { markerSize, markerInset } = config.aruco;
	const farX = designWidth - markerInset - markerSize;
	const farY = designHeight - markerInset - markerSize;
	return [
		markerPlacement('tl', config.aruco.anchorIds.topLeft, markerInset, markerInset, config),
		markerPlacement('tr', config.aruco.anchorIds.topRight, farX, markerInset, config),
		markerPlacement('br', config.aruco.anchorIds.bottomRight, farX, farY, config),
		markerPlacement('bl', arucoFormatVersionMarkerId(config), markerInset, farY, config),
	];
}

function markerPlacement(
	corner: OmrCorner,
	id: number,
	x: number,
	y: number,
	config: OmrConfig
): ArucoMarkerPlacement {
	return {
		corner,
		id,
		x,
		y,
		width: config.aruco.markerSize,
		height: config.aruco.markerSize,
	};
}

/** Curated marker id assigned to a format version by the given config's pool. */
export function arucoFormatVersionMarkerId(config: OmrConfig): number {
	const markerId = config.aruco.formatVersionIds[config.version - 1];
	if (markerId === undefined) {
		throw new Error(`Brak markera ArUco dla formatu karty odpowiedzi v${config.version}.`);
	}
	return markerId;
}

/**
 * Return the one-based answer-sheet format version encoded by a curated marker
 * id, or `undefined` when the id is not part of the version pool.
 */
export function answerSheetFormatVersionFromMarkerId(
	markerId: number,
	config: OmrConfig = LATEST_OMR_CONFIG
): number | undefined {
	const index = config.aruco.formatVersionIds.indexOf(markerId);
	return index === -1 ? undefined : index + 1;
}

/**
 * Resolve the format version (and its config) from a detected bottom-left
 * version marker id, searching every known configuration. Returns `undefined`
 * when the id is not a version marker in any known format.
 */
export function omrVersionFromMarkerId(markerId: number): number | undefined {
	for (const config of OMR_CONFIG_VERSIONS) {
		const version = answerSheetFormatVersionFromMarkerId(markerId, config);
		if (version !== undefined) return version;
	}
	return undefined;
}

/** Placement of the metadata QR code, in design units. */
export function metadataQrPlacement(config: OmrConfig): OmrRect {
	const { designWidth, designHeight } = config.geometry;
	const { markerSize, markerInset } = config.aruco;
	const { size } = config.qrCode;
	return {
		x: designWidth - markerInset - size,
		y: designHeight - markerSize - config.grid.exclusionPadding * 2 - markerInset - size,
		width: size,
		height: size,
	};
}

/**
 * The full answer grid design plane. Future bubbles may use this whole area as
 * long as they avoid `omrExclusionZones(...)`.
 */
export function gridArea(config: OmrConfig): OmrRect {
	return {
		x: 0,
		y: 0,
		width: config.geometry.designWidth,
		height: config.geometry.designHeight,
	};
}

/** Reserved areas future bubble/grid content must avoid. */
export function omrExclusionZones(config: OmrConfig): OmrExclusionZone[] {
	return [
		...arucoMarkerPlacements(config).map((marker) =>
			exclusionZone(config, `aruco-${marker.corner}`, marker)
		),
		exclusionZone(config, 'metadata-qr', metadataQrPlacement(config)),
	];
}

function exclusionZone(config: OmrConfig, key: string, rect: OmrRect): OmrExclusionZone {
	const { designWidth, designHeight } = config.geometry;
	const padding = config.grid.exclusionPadding;
	return {
		key,
		x: Math.max(0, rect.x - padding),
		y: Math.max(0, rect.y - padding),
		width: Math.min(designWidth, rect.x + rect.width + padding) - Math.max(0, rect.x - padding),
		height: Math.min(designHeight, rect.y + rect.height + padding) - Math.max(0, rect.y - padding),
	};
}

/** Convert design units to millimetres. */
export function omrUnitsToMm(config: OmrConfig, units: number): number {
	return units / config.geometry.unitsPerMm;
}
