<script lang="ts">
	import FixedCanvas from '@/lib/ui/FixedCanvas.svelte';
	import { arucoMarkerSvg } from '@/utils/aruco';
	import {
		arucoMarkerPlacements,
		gridArea,
		LATEST_OMR_CONFIG,
		metadataQrPlacement,
		omrExclusionZones,
	} from '@/utils/omr';
	import { LINE_HEIGHT_MM } from '@/utils/paper';
	import { qrCodeSvg } from '@/utils/qrcode';

	interface Props {
		testName?: string;
		revisionName?: string;
		revisionId: string;
		/** Number of answer options per question (the OMR grid calculation data). */
		answersPerQuestion?: number[];
	}

	let { testName = '', revisionName = '', revisionId, answersPerQuestion = [] }: Props = $props();

	/** Instruction block always reserves exactly this many lines of height. */
	const INSTRUCTION_LINES = 6;

	const omrConfig = LATEST_OMR_CONFIG;
	const grid = gridArea(omrConfig);
	/** Bounding rectangle of the answer-grid area generated by the OMR grid block. */
	const gridBounds = omrConfig.grid.calculateGridBounds(omrConfig);
	const qrPlacement = metadataQrPlacement(omrConfig);
	const exclusionZones = omrExclusionZones(omrConfig);

	/** Column rectangles for the answer grid, one per question block. */
	const gridColumns = $derived(
		omrConfig.grid.calculateGridColumns(omrConfig, gridBounds, answersPerQuestion)
	);

	let metadataQr = $state<string | null>(null);
	let markerSvgs = $state<
		Array<ReturnType<typeof arucoMarkerPlacements>[number] & { svg: string }>
	>([]);

	// OpenCV.js loads asynchronously, so the marker/QR SVGs are generated once
	// the wasm is ready. The print flow must wait for these to be populated.
	$effect(() => {
		const payload = omrConfig.qrCode.encodePayload({
			revisionId,
		});
		const placements = arucoMarkerPlacements(omrConfig);
		let cancelled = false;

		Promise.all([
			qrCodeSvg(payload),
			...placements.map((marker) => arucoMarkerSvg(marker.id)),
		]).then(([qr, ...markerSvgList]) => {
			if (cancelled) return;
			metadataQr = qr;
			markerSvgs = placements.map((marker, index) => ({
				...marker,
				svg: markerSvgList[index],
			}));
		});

		return () => {
			cancelled = true;
		};
	});
</script>

<div class="answer-sheet">
	<header class="sheet-header">
		<div class="sheet-header-test">{testName}</div>
		<div class="sheet-header-revision">{revisionName}</div>
	</header>

	<section
		class="instructions"
		style:height="{INSTRUCTION_LINES * LINE_HEIGHT_MM}mm"
		aria-label="Instrukcja wypełniania karty odpowiedzi"
	>
		<p class="instructions-title">Jak wypełnić kartę odpowiedzi?</p>
		<ul>
			<li>Wypełniaj kółka całkowicie, używając ciemnego długopisu lub ołówka.</li>
			<li>Przy każdym pytaniu zaznacz dokładnie jedną odpowiedź.</li>
			<li>Aby zmienić odpowiedź, przekreśl błędnie wypełnione kółko i zaznacz nowe.</li>
			<li>Nie zapisuj rogów karty ani kodów — są potrzebne do automatycznego skanowania.</li>
		</ul>
	</section>

	<FixedCanvas
		class="omr-block"
		designWidth={omrConfig.geometry.designWidth}
		designHeight={omrConfig.geometry.designHeight}
		widthMm={omrConfig.geometry.blockWidthMm}
	>
		<div
			class="omr-grid-plane"
			style:left="{grid.x}px"
			style:top="{grid.y}px"
			style:width="{grid.width}px"
			style:height="{grid.height}px"
		>
			<span>Obszar siatki odpowiedzi (z wyłączeniami)</span>
		</div>

		<!-- Visual outline of the answer-grid bounds produced by `sheetAnswerGrid` —
		     temporary aid to confirm the generated geometry. -->
		<div
			class="omr-grid-bounds"
			style:left="{gridBounds.x}px"
			style:top="{gridBounds.y}px"
			style:width="{gridBounds.width}px"
			style:height="{gridBounds.height}px"
			aria-hidden="true"
		></div>

		<!-- Answer grid columns produced by `calculateGridColumns`. Each column is a
		     square-cell grid: a header row (Lp. + answer letters) followed by one
		     row per question (number + centered inner-square answer boxes). -->
		{#each gridColumns as col (col.questionNumberStart)}
			{#if col.questionAnswerBoxes.length > 0}
				{@const rowSize = omrConfig.grid.gridElementSize}
				{@const letterCount = Math.max(...col.questionAnswerBoxes)}
				<!-- Header row: "Lp." column label + A, B, C, … -->
				{#each Array.from({ length: letterCount + 1 }, (_, i) => i) as cellCol (cellCol)}
					<div
						class="omr-grid-cell omr-grid-cell--header"
						style:left="{col.x + cellCol * rowSize}px"
						style:top="{col.y}px"
						style:width="{rowSize}px"
						style:height="{rowSize}px"
					>
						{cellCol === 0 ? 'Lp.' : String.fromCharCode(64 + cellCol)}
					</div>
				{/each}
				<!-- A row per question: number cell + one answer box per option. -->
				{#each col.questionAnswerBoxes as answerCount, row (row)}
					{@const questionY = col.y + (row + 1) * rowSize}
					<div
						class="omr-grid-cell omr-grid-cell--number"
						style:left="{col.x}px"
						style:top="{questionY}px"
						style:width="{rowSize}px"
						style:height="{rowSize}px"
					>
						{col.questionNumberStart + row + 1}
					</div>
					{#each Array.from({ length: answerCount }, (_, i) => i) as answer (answer)}
						{@const innerGap = (rowSize - omrConfig.grid.gridElementInternalSquareSize) / 2}
						<div
							class="omr-grid-answer"
							style:left="{col.x + (answer + 1) * rowSize}px"
							style:top="{questionY}px"
							style:width="{rowSize}px"
							style:height="{rowSize}px"
						>
							<div
								class="omr-grid-answer-inner"
								style:left="{innerGap}px"
								style:top="{innerGap}px"
								style:width="{omrConfig.grid.gridElementInternalSquareSize}px"
								style:height="{omrConfig.grid.gridElementInternalSquareSize}px"
							></div>
						</div>
					{/each}
				{/each}
			{/if}
		{/each}

		{#each exclusionZones as zone (zone.key)}
			<div
				class="omr-exclusion-zone"
				style:left="{zone.x}px"
				style:top="{zone.y}px"
				style:width="{zone.width}px"
				style:height="{zone.height}px"
				aria-hidden="true"
			></div>
		{/each}

		{#each markerSvgs as marker (marker.id)}
			<div
				class="omr-marker"
				style:left="{marker.x}px"
				style:top="{marker.y}px"
				style:width="{omrConfig.aruco.markerSize}px"
				style:height="{omrConfig.aruco.markerSize}px"
			>
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html marker.svg}
			</div>
		{/each}

		<div
			class="omr-qr"
			style:left="{qrPlacement.x}px"
			style:top="{qrPlacement.y}px"
			style:width="{omrConfig.qrCode.size}px"
			style:height="{omrConfig.qrCode.size}px"
		>
			<!-- eslint-disable-next-line svelte/no-at-html-tags -->
			{@html metadataQr}
		</div>
	</FixedCanvas>
</div>

<style>
	.answer-sheet {
		font-family: Georgia, 'Times New Roman', Times, serif;
		font-size: var(--print-font, 12pt);
		line-height: 1.4;
		color: #000000;
		display: flex;
		flex-direction: column;
		gap: 4mm;
		height: 100%;
	}

	/* Mirrors the question sheet header so both pages can be compared visually. */
	.sheet-header {
		display: flex;
		flex-direction: column;
		gap: 1mm;
		padding-bottom: 2mm;
		border-bottom: 0.5pt solid #000000;
	}

	.sheet-header-test {
		font-size: 16pt;
		font-weight: 700;
	}

	.sheet-header-revision {
		font-weight: 700;
	}

	.instructions {
		overflow: hidden;
	}

	.instructions-title {
		font-weight: 700;
		margin: 0;
	}

	.instructions ul {
		margin: 0;
		padding-left: 6mm;
	}

	.omr-marker,
	.omr-qr,
	.omr-grid-plane,
	.omr-grid-bounds,
	.omr-grid-cell,
	.omr-grid-answer,
	.omr-exclusion-zone {
		position: absolute;
	}

	/* The generated SVGs carry no width/height attributes — stretch them to
	   their positioned containers. */
	.omr-marker :global(svg),
	.omr-qr :global(svg) {
		display: block;
		width: 100%;
		height: 100%;
	}

	.omr-grid-plane {
		border: 4px dashed #999999;
		box-sizing: border-box;
		display: flex;
		align-items: center;
		justify-content: center;
		color: #999999;
		font-size: 40px;
	}

	.omr-grid-bounds {
		box-sizing: border-box;
		pointer-events: none;
	}

	.omr-grid-cell {
		box-sizing: border-box;
		border: 1px solid #000000;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 40px;
	}

	.omr-grid-cell--header {
		font-weight: 700;
	}

	.omr-grid-answer {
		box-sizing: border-box;
		border: 1px solid #000000;
	}

	/* Centered selectable square inside each outer answer cell. */
	.omr-grid-answer-inner {
		position: absolute;
		box-sizing: border-box;
		border: 1px solid #000000;
	}

	.omr-exclusion-zone {
		border: 4px dashed #999999;
		box-sizing: border-box;
		display: flex;
		align-items: flex-start;
		justify-content: center;
		color: #777777;
		padding-top: 6px;
	}
</style>
